name: Test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Deps
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
